### ISSUE TITLE
PyHEP 2022 "proceedings"

### ISSUE THREAD

**Issue by eduardo-rodrigues** [goi42/pythia8_python_interface_pyHEP_2022#1]
Hello @goi42, I see that you already have a DOI for your PyHEP 2022 talk. Can you then "attach it" in Zenodo to the pyhep2022 community so as to be part of the "proceedings"? I will get a ping to curate and accept.

Also nicer if you update the title of the Zenodo page to the actual talk title ;-).

Many thanks.

**Comment by goi42** [comment]
done

**Comment by eduardo-rodrigues** [comment]
I'm afraid you did not edit your Zenodo entry to be linked/attached to the workshop community as I got nothing to curate and you can clearly see from https://zenodo.org/communities/pyhep2022/ that it's not there. You need to log in to Zenodo to request this.

**Comment by goi42** [comment]
I'm not sure why it doesn't appear. I edited it and selected the pyHEP 2022 community, as you can see.
<img width="953" alt="image" src="https://user-images.githubusercontent.com/15774838/193686656-85be2be6-f4ce-47a3-8e39-4816056168ab.png">

**Comment by goi42** [comment]
I have tried clicking "publish" instead of "save", but I still do not find it in the community. 🤷🏼‍♂️

**Comment by eduardo-rodrigues** [comment]
The above is correct and the first step. Then you need to save and publish as for anything on Zenodo. It can seem odd but that's how Zenodo works. Anything that is not saved before cannot be published. And if you only save it is kept like that but never gets online. See it as git commit and the actual git push ;-).

**Comment by goi42** [comment]
So is it properly organized now?

**Comment by eduardo-rodrigues** [comment]
Yes, got the ping to curate and accepted your contribution. All done.
